apiVersion: v1
kind: Service
metadata:
  name: email-svc
  namespace: communication
  labels: &EmailLabels
    app: emails
    tier: backend
    role: communication
    component: emails
spec:
  ports:
  - port: 4000
    name: http
    targetPort: 4000
  selector: *EmailLabels
