apiVersion: v1
kind: Service
metadata:
  name: email-svc
  namespace: comms
  labels: &EmailLabels
    app: emails
    tier: backend
    role: communication
    component: emails
spec:
  ports:
  - port: 6000
    name: http
    targetPort: http
  selector: *EmailLabels
