apiVersion: apps/v1
kind: Deployment
metadata:
    name: email-api
    namespace: communication
    labels: &EmailLabels
        app: emails
        tier: backend
        role: communication
        component: emails
spec:
    selector:
        matchLabels: *EmailLabels
    replicas: 1
    template:
        metadata:
            labels: *EmailLabels
        spec:
            securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 3000
                fsGroup: 2000

            containers:
                -   name: email-gateway
                    image: garihublimited/email-gateway:latest
                    imagePullPolicy: Always
                    readinessProbe:
                        httpGet:
                            path: /health
                            port: 4000
                    ports:
                        -   containerPort: 4000
                    env:
                        -   name: FLASK_ENV
                            value: "staging"
                        -   name: PORT
                            value: "4000"

                        -   name: USERNAME
                            valueFrom:
                                secretKeyRef:
                                    name: email-config
                                    key: username

                        -   name: PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: email-config
                                    key: password

                        -   name: HOST
                            valueFrom:
                                secretKeyRef:
                                    name: email-config
                                    key: host

                        -   name: SMTPPORT
                            valueFrom:
                                secretKeyRef:
                                    name: email-config
                                    key: smtpport

                        -   name: SENDEREMAILADDRESS
                            valueFrom:
                                secretKeyRef:
                                    name: email-config
                                    key: senderEmailAddress

                        -   name: SENDEREMAILNAME
                            valueFrom:
                                secretKeyRef:
                                    name: email-config
                                    key: senderEmailName


                        -   name: MAIL_TOKEN
                            valueFrom:
                                secretKeyRef:
                                    name: email-config
                                    key: token

                        -   name: MAIL_API_URL
                            valueFrom:
                                secretKeyRef:
                                    name: email-config
                                    key: apiUrl

                        -   name: BROKER_USER
                            valueFrom:
                                secretKeyRef:
                                    name: email-amqp-credentials
                                    key: user

                        -   name: BROKER_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: email-amqp-credentials
                                    key: password

                        -   name: BROKER_HOST
                            value: 'rabbitmq-discovery'

                        -   name: BROKER_URL
                            value: 'amqp://$(BROKER_USER):$(BROKER_PASSWORD)@$(BROKER_HOST):5672//'

                        -   name: RESULT_BACKEND
                            value: 'redis://redis:6379'